### ISSUE TITLE
Service fails to start with KafkaHttpMetricsReporter enabled: java.lang.NoClassDefFoundError: com/yammer/metrics/reporting/AdminServlet

### ISSUE THREAD

**Issue by turtlemonvh** [arnobroekhof/kafka-http-metrics-reporter#5]
Error logs

```
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: [2017-04-03 15:35:30,232] INFO Initializing Kafka Http Metrics Reporter (nl.techop.kafka.KafkaHttpMetricsServer)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: [2017-04-03 15:35:30,247] INFO Logging initialized @523ms (org.eclipse.jetty.util.log)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: [2017-04-03 15:35:30,288] FATAL  (kafka.Kafka$)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: java.lang.NoClassDefFoundError: com/yammer/metrics/reporting/AdminServlet
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: at nl.techop.kafka.KafkaHttpMetricsServer.init(KafkaHttpMetricsServer.java:78)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: at nl.techop.kafka.KafkaHttpMetricsServer.<init>(KafkaHttpMetricsServer.java:55)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: at nl.techop.kafka.KafkaHttpMetricsReporter.init(KafkaHttpMetricsReporter.java:62)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: at kafka.metrics.KafkaMetricsReporter$$anonfun$startReporters$1.apply(KafkaMetricsReporter.scala:66)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: at kafka.metrics.KafkaMetricsReporter$$anonfun$startReporters$1.apply(KafkaMetricsReporter.scala:64)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: at kafka.metrics.KafkaMetricsReporter$.startReporters(KafkaMetricsReporter.scala:64)
Apr  3 15:35:30 kafka-1a-01 kafka-server-start.sh[23377]: at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:27)
Apr  3 15:35:30 kafka-1a-01 systemd[1]: kafka.service: main process exited, code=exited, status=1/FAILURE
Apr  3 15:35:30 kafka-1a-01 systemd[1]: Unit kafka.service entered failed state.
Apr  3 15:35:30 kafka-1a-01 systemd[1]: kafka.service failed.
```

Install process:

```bash
# Download zip archive and build
wget https://github.com/arnobroekhof/kafka-http-metrics-reporter/archive/kafka_2.12-0.10.2.0.zip
unzip kafka_2.12-0.10.2.0.zip
cd kafka-http-metrics-reporter-kafka_2.12-0.10.2.0
mvn package

# Copy jar into `/libs` directory with other jars
cp target/kafka-http-metrics-reporter-0.10.2.0.jar /opt/kafka/kafka_2.11-0.10.2.0/libs/

# Edit kafka properties file
cat >> cat /opt/kafka/kafka_2.11-0.10.2.0/config/kafka.properties << EOF
############################# Metrics #############################
kafka.metrics.reporters=nl.techop.kafka.KafkaHttpMetricsReporter
kafka.http.metrics.reporter.enabled=true
kafka.http.metrics.host=localhost
kafka.http.metrics.port=8897
EOF

# Restart
service kafka restart
```

Maven version

```bash
mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/local/apache-maven
Java version: 1.8.0_74, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_74/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-229.11.1.el7.x86_64", arch: "amd64", family: "unix"
```

**Comment by cxy2916982** [comment]
i have same error, did you fix it?

**Comment by napsterX** [comment]
Any fix for this? I am facing the same issue :|

**Comment by turtlemonvh** [comment]
I ended up using [JMX trans](https://github.com/jmxtrans/jmxtrans) to grab metric information instead.
