### ISSUE TITLE
/api/metrics fails with Kafka 1.0 and Java 9

### ISSUE THREAD

**Issue by manderson23** [arnobroekhof/kafka-http-metrics-reporter#8]
The following exception is visible in the broker logs

> [2017-11-13 10:20:52,018] WARN /api/metrics (org.eclipse.jetty.servlet.ServletHandler)
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getOpenFileDescriptorCount() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @141e5bef
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at com.yammer.metrics.core.VirtualMachineMetrics.fileDescriptorUsage(VirtualMachineMetrics.java:257)
	at com.yammer.metrics.reporting.MetricsServlet.writeVmMetrics(MetricsServlet.java:253)
	at com.yammer.metrics.reporting.MetricsServlet.doGet(MetricsServlet.java:175)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by azunke** [comment]
Hey, I am also facing the same issue. Did you get anything related to the issue?

**Comment by MrMoronIV** [comment]
does this mean this package doesn't work anymore in later versions?

**Comment by MrMoronIV** [comment]
In other words, this project is dead no?

**Comment by manderson23** [comment]
@MrMoronIV looks like it. Most people seem to use Prometheus JMX exporter for Kafka metrics.
